### ISSUE TITLE
assimp/assimp

### ISSUE THREAD

**Issue by nikhedonia** [LoopPerfect/buckaroo-wishlist#25] opened 2017-04-28 13:33 UTC
https://github.com/assimp/assimp
supports many 3D file formats

**Comment by njlr** [comment] 2017-04-28 13:36
Duplicate of [https://github.com/LoopPerfect/buckaroo-wishlist/issues/23](https://github.com/LoopPerfect/buckaroo-wishlist/issues/23 )

**Closed** 2017-04-28 13:35 UTC
Labels: duplicate
